#!/bin/busybox sh

delay=0.01
progress_bar_length=20
echo -ne "\033[?25l"
# /bin/busybox echo -ne "Wait for initialized... /"
# for i in {1..10}; do
#     /bin/busybox sleep $delay
#     /bin/busybox echo -ne "\b\\"
#     /bin/busybox sleep $delay
#     /bin/busybox echo -ne "\b/"
# done

for i in $(/bin/busybox seq 0 $progress_bar_length); do
    /bin/busybox echo -ne "\r"
    /bin/busybox echo -ne "Wait for initialized... [\033[32m"
    for j in $(/bin/busybox seq 0 $(($i - 1))); do
        /bin/busybox echo -ne "="
    done
    if [ $i -lt $progress_bar_length ]; then
        /bin/busybox echo -ne ">\033[0m"
    else
        /bin/busybox echo -ne "=\033[0m"
    fi
    for j in $(/bin/busybox seq $i $(($progress_bar_length - 1))); do
        /bin/busybox echo -ne " "
    done
    /bin/busybox echo -ne "]"
    /bin/busybox sleep $delay
done

echo -ne "\033[?25h"
c1="arch ash base64 cat chattr chgrp chmod chown conspy cp cpio cttyhack date dd df dmesg dnsdomainname dumpkmap echo ed egrep false fatattr fdflush fgrep fsync getopt grep gunzip gzip hostname hush ionice iostat ipcalc kbd_mode kill link linux32 linux64 ln login ls lsattr lzop makemime mkdir mknod mktemp more mount mountpoint mpstat mt mv netstat nice nuke pidof ping ping6 pipe_progress printenv ps pwd reformime resume rev rm rmdir rpm run-parts scriptreplay sed setarch setpriv setserial sh sleep stat stty su sync tar touch true umount uname usleep vi watch zcat"
c2="[ [[ awk basename bc beep blkdiscard bunzip2 bzcat bzip2 cal chpst chrt chvt cksum clear cmp comm crontab cryptpw cut dc deallocvt diff dirname dos2unix dpkg dpkg-deb du dumpleases eject env envdir envuidgid expand expr factor fallocate fgconsole find flock fold free ftpget ftpput fuser groups hd head hexdump hexedit hostid id install ipcrm ipcs killall last less logger logname lpq lpr lsof lspci lsscsi lsusb lzcat lzma man md5sum mesg microcom mkfifo mkpasswd nc nl nmeter nohup nproc nsenter nslookup od openvt passwd paste patch pgrep pkill pmap printf pscan"
c3="pstree pwdx readlink realpath renice reset resize rpm2cpio runsv runsvdir rx script seq setfattr setkeycodes setsid setuidgid sha1sum sha256sum sha3sum sha512sum showkey shred shuf smemcap softlimit sort split ssl_client strings sum sv svc svok tac tail taskset tcpsvd tee telnet test tftp time timeout top tr traceroute traceroute6 truncate ts tty ttysize udhcpc6 udpsvd unexpand uniq unix2dos unlink unlzma unshare unxz unzip uptime users uudecode uuencode vlock volname w wall wc wget which who whoami whois xargs xxd xz xzcat yes"
for cmd in $c1 $c2 $c3; do
  /bin/busybox ln -s /bin/busybox /bin/$cmd
done
mkdir -p /proc && mount -t proc  none /proc # 提供系统进程和内核信息。
mkdir -p /sys  && mount -t sysfs none /sys  # 虚拟文件系统
# mknod /dev/sda b 8 0
# mkdir -p /newroot
# mount -t ext2 /dev/sda /newroot

if [ ! -f /etc/passwd ]; then
    echo "Creating /etc/passwd file..."
    mkdir /etc
    echo "root:x:0:0:root:/root:/bin/sh" > /etc/passwd
    echo "root:x:0:" > /etc/group
fi
# export TZ=Asia/Shanghai
# export PS1='(linux-minimal) '
export PATH=/sbin:/usr/sbin:/bin:/usr/bin

clear

echo -ne "Welcome to \033[1;32mlinux-minimal\033[0m, " # /bin/busybox echo Welcome to linux-minimal!
echo -ne $(whoami) | awk '{printf "you are \033[1;33m%s\033[0m user.\n", $1}'
echo -e "Type \033[32mls\033[0m to see this OS"
# /bin/busybox ln -s /bin/busybox /ls
# /bin/busybox echo $(/bin/busybox whoami) | /bin/busybox awk '{printf "You are \033[1;33m%s\033[0m\n", $1}'
# sh # /bin/busybox sh # which no return
/bin/mysh # which no return


# mount
# top 
# du -k | sort -nr | awk '{printf "%5.2fMB\t%s\n", $1/1024, $2}' | head -n 8 
# df -h 
